### ISSUE TITLE
dexmaker-mockito-inline build fails with Cannot notify listeners of type ProjectEvaluationListener as these listeners are already being notified.

### ISSUE THREAD

**Issue by moltmann** [linkedin/dexmaker#101]
This only happens when syncing gradle files from inside Android Studio. ./gradlew build works. Downgrading to org.jfrog.buildinfo:build-info-extractor-gradle:4.3.0 causes other failures.

This seems to be https://github.com/JFrogDev/build-info/issues/86

---

Error:FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/google/home/moltmann/projects/dexmaker/dexmaker-mockito-inline/build.gradle' line: 66

* What went wrong:
A problem occurred configuring project ':dexmaker-mockito-inline'.
> Failed to notify project evaluation listener.
   > A problem occurred configuring project ':dexmaker'.
      > Cannot notify listeners of type ProjectEvaluationListener as these listeners are already being notified.
   > A problem occurred configuring project ':dexmaker'.
      > Cannot notify listeners of type ProjectEvaluationListener as these listeners are already being notified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

---

@drewhannay Any idea how we can work around this?

**Comment by drewhannay** [comment]
@moltmann I was seeing this too, but didn't have time to investigate yet. Is #102 supposed to fix this?

**Comment by moltmann** [comment]
No. #102 fixes issues when running the tests out of Android Studio. AS really does not like symlinks. As as I understand there seem to be two solutions to this.
- Downgrade to org.jfrog.buildinfo:build-info-extractor-gradle:4.3.0
- Move all the publishing into the top level gradle file
