### ISSUE TITLE
Please publish to jcenter

### ISSUE THREAD

**Issue by philipa** [linkedin/dexmaker#121]
Please consider publishing dexmaker to jcenter as documented here: https://www.jfrog.com/confluence/display/BT/Central+Repositories#CentralRepositories-IncludingyourPackageinJCenter

The jcenter repository is accessible anonymously, whereas bintray requires an account.

**Comment by drewhannay** [comment]
As far as I know, this is already done. Are you having an issue with accessing the artifacts?

**Comment by philipa** [comment]
Yes. 

Also, I can't find them by searching at https://bintray.com/bintray/jcenter or browsing at http://jcenter.bintray.com/

**Comment by drewhannay** [comment]
Here's the four artifact links. They all show up as "Linked to jcenter" for me.

https://bintray.com/linkedin/maven/dexmaker
https://bintray.com/linkedin/maven/dexmaker-mockito
https://bintray.com/linkedin/maven/dexmaker-mockito-inline
https://bintray.com/linkedin/maven/dexmaker-mockito-inline-extended

**Comment by philipa** [comment]
... and now it works! I've got nexus in the middle, perhaps that had a glitch.

Thanks for the fast support.
