### ISSUE TITLE
Incompatible with Gradle 5

### ISSUE THREAD

**Issue by Mygod** [linkedin/dexmaker#131]
Errs: `Unresolved reference: ProxyBuilder`.

Example build: https://circleci.com/gh/Mygod/VPNHotspot/89

**Comment by Mygod** [comment]
Still present on Gradle 5.1.

**Comment by drewhannay** [comment]
I'm not clear how this could be an issue with Gradle 5. We're using Gradle 5.0 + dexmaker-mockito and not seeing any issues. Any other information you can provide?

**Comment by Mygod** [comment]
That's weird. You can find source code [here](https://github.com/Mygod/VPNHotspot) and see my example build. It errs on `ProxyBuilder` not found. And going back to 4.10.2 fixes this. I have no idea why that is.

**Comment by Mygod** [comment]
Still present on 5.1.1.

**Comment by Mygod** [comment]
You can checkout the source code here and see what's wrong: https://github.com/Mygod/VPNHotspot

**Comment by hongbinh** [comment]
@Mygod , I downloaded your code and saw the issue, but I believe it's more related to how your project is setup, I'd suggest you check out this gradle doc and see whether anything can give you a clue: https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#changes_5.0

**Comment by hongbinh** [comment]
@Mygod , adding below line to your build.gradle should solve your problem:
    implementation 'com.linkedin.dexmaker:dexmaker:2.19.1'

**Comment by drewhannay** [comment]
I think that's probably the right solution. I don't think dexmaker-mockito intends to expose dexmaker as part of its public API. Adding the dependency explicitly seems like a good option here.

**Comment by Mygod** [comment]
Replacing `dexmaker-mockito` with `dexmaker` fixes this. Nice! Thanks.
