### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by TimvdLippe** [linkedin/dexmaker#133]
Could you publish a new release? Quite some commits were introduced since the last one, and I mostly interested in https://github.com/linkedin/dexmaker/commit/1e417ef320f876c7011a5aef674a0af6bfe07c74 so that I can remove my fork. Thanks!

**Comment by drewhannay** [comment]
Sure, I'll try to take a look at this tomorrow or over the weekend.

**Comment by drewhannay** [comment]
[2.21.0](https://github.com/linkedin/dexmaker/releases/tag/2.21.0) has been published!
