### ISSUE TITLE
2.21.0 was not published to the maven central repository

### ISSUE THREAD

**Issue by TimvdLippe** [linkedin/dexmaker#140]
https://mvnrepository.com/artifact/com.linkedin.dexmaker/dexmaker-mockito 2.21.0 was published to JCenter only. Could this version (and future versions) be published to Maven Central as well?

**Comment by TimvdLippe** [comment]
Note that the maven central repository links to the Spring Plugins repository.

**Comment by drewhannay** [comment]
Starting with [2.28.1](https://github.com/linkedin/dexmaker/releases/tag/2.28.1), all versions will be published to Maven Central. Sorry that it took JCenter shutting down for us to get around to this 😓
