### ISSUE TITLE
Received status code 501 from server: HTTPS Required

### ISSUE THREAD

**Issue by zengxiaoshi** [linkedin/dexmaker#160]
**Could not GET 'http://repo.maven.apache.org/maven2/com/linkedin/dexmaker/dexmaker-mockito-inline-extended/2.25.1/dexmaker-mockito-inline-extended-2.25.1.pom'. 
Received status code 501 from server: HTTPS Required

Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.**

If you're receiving this error, then you need to replace all URL references to Maven Central with their canonical HTTPS counterparts:

Replace http://repo1.maven.org/maven2/ with https://repo1.maven.org/maven2/

Replace http://repo.maven.apache.org/maven2/ with https://repo.maven.apache.org/maven2/

If for any reason your environment cannot support HTTPS, you have the option of using our dedicated insecure endpoint at http://insecure.repo1.maven.org/maven2/

For further context around the move to HTTPS, please see https://blog.sonatype.com/central-repository-moving-to-https.

**Comment by drewhannay** [comment]
Hi @zengxiaoshi , can you clarify what issue you're having? Dexmaker is not published to Maven Central, only JCenter.

**Comment by drewhannay** [comment]
Starting with [2.28.1](https://github.com/linkedin/dexmaker/releases/tag/2.28.1), all versions will be published to Maven Central.
