### ISSUE TITLE
Does not introduce transitive dependency of mockito per README

### ISSUE THREAD

**Issue by chao2zhang** [linkedin/dexmaker#166]
In the README.md, there is the following:
`Note: The dependency on Mockito will be transitively included, so there's no need to specify both Mockito AND dexmaker-mockito`

However, in dexmaker-mockito/build.gradle, mockito dependency is implementation, not API.
Therefore adding `androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito:2.25.1'` does not introduce the mockito dependency transitively

**Comment by drewhannay** [comment]
This is probably left over from before `api` and `implementation` were a thing in Gradle.

Do you think we should change the documentation or should we change the dependency to `api`? I probably prefer the latter.

**Comment by chao2zhang** [comment]
Latter is also preferred from me because clients need to keep the dexmaker version in sync with mockito's, which is difficult for dexmaker 2.28.0 because it really depends on mocktio 2.28.2
