### ISSUE TITLE
[URGENT] Library is not downloadable from maven

### ISSUE THREAD

**Issue by kaarthicksiyer** [linkedin/dexmaker#194]
It seems the library is not available from maven or jitpack. Please help to check

`Execution failed for task ':app:mergeProdDebugResources'.
> Could not resolve all files for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not find com.linkedin.dexmaker:dexmaker-mockito:2.25.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom
       - https://dl.google.com/dl/android/maven2/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom
       - https://jitpack.io/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom
       - https://clojars.org/repo/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom
       - https://oss.sonatype.org/content/repositories/ksoap2-android-releases/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom
       - https://maven.google.com/com/linkedin/dexmaker/dexmaker-mockito/2.25.0/dexmaker-mockito-2.25.0.pom`

**Comment by drewhannay** [comment]
This library didn't publish to maven central before version [2.28.1](https://github.com/linkedin/dexmaker/releases/tag/2.28.1)

Can you try using the latest version instead? [2.28.4](https://github.com/linkedin/dexmaker/releases/tag/2.28.4)

**Comment by kaarthicksiyer** [comment]
@drewhannay that is really weird. I started to encounter issues only after i cleared my android studio cache. Until then I never encountered this issue and we have been using 2.25.0 version since 2020. But your solution worked so thanks a lot
