### ISSUE TITLE
DexmakerMockMaker incompatible with Mockito 2.0 MockMaker

### ISSUE THREAD

**Issue by andyp1per** [linkedin/dexmaker#23]
MockMaker now includes isTypeMockable. I can't get this working with annotations for this reason.

**Comment by dbacinski** [comment]
+1

**Comment by ultraon** [comment]
+1
Since mockito version 2.0.18-beta i have this issue.
With mockito version 2.0.17-beta it works well.

**Comment by eygraber** [comment]
I've created https://github.com/crittercism/dexmaker/pull/33 to bring support for Mockito 2 (against version 2.1.0-beta.120).

I've verified that it compiles, but that's about it as of now.

**Comment by niltonvasques** [comment]
+1

**Comment by drewhannay** [comment]
Fixed with #52
