### ISSUE TITLE
Does dexmaker work for Art?

### ISSUE THREAD

**Issue by jophde** [linkedin/dexmaker#4]
Or does it only work for Dalvik?  I am particularly interested in using it to proxy public methods in concrete classes.

**Comment by dshirley** [comment]
Based on our testing it does work with Art.  When loading the .dex file, Art will automagically perform a compilation step before loading it.

**Comment by jophde** [comment]
Also, is it even possible to do bytecode manipulation on classes that are part of the Android runtime on the device?

**Comment by dshirley** [comment]
I'm not entirely sure how the new Android Runtime works, but previously, almost all of the basic java classes (full list here:  https://android.googlesource.com/platform/frameworks/base.git/+/master/preloaded-classes) are preloaded by the zygote process.  New processes are forked from Zygote, and thus receive a copy of a system ClassLoader (http://developer.android.com/reference/java/lang/ClassLoader.html#getSystemClassLoader()) that already has these classes loaded.  Therefore, it isn't possible to modify these classes on the fly.

However, DexMaker allows subclassing the base system classes by generating a new dex file at runtime.  The dynamically generated subclass can then be used to in the same way the base class would.

**Comment by nvictor** [comment]
@dshirley re: dynamic bytecode manipulation. what about user defined classes?

**Comment by drewhannay** [comment]
Proxying user defined classes by subclassing should work in the same way as it does for base system classes.
