### ISSUE TITLE
ProxyBuilder does not correctly traverse hierarchy for extra interfaces

### ISSUE THREAD

**Issue by paulduffin** [linkedin/dexmaker#61]
When using Mockito to mock a class with an extra interface Foo which itself extended interface Bar any attempt to call methods on Bar would result in an AbstractMethodError. e.g.

class Baz {
}

interface Foo extends Bar {
    String foo();
}

interface Bar {
    int bar();
}

Baz bazMock = mock(Baz.class, withSettings().extraInterfaces(Foo.class))
when(((Foo) bazMock).bar()).thenReturn(4); <-- AbstractMethodError when calling bar().

This is because when ProxyBuilder is collecting the set of methods for which it needs to generate stubs it does not check the interfaces extended by the extra interfaces.

**Comment by drewhannay** [comment]
Thanks for picking this up.
