### ISSUE TITLE
Avoiding Mockito internal APIs

### ISSUE THREAD

**Issue by mockitoguy** [linkedin/dexmaker#64]
Hey guys!

Dexmaker is using internal Mockito APIs, are you interested in working together to clean this up?

While working on extending Mockito APIs so that it is easier to integrate (https://github.com/mockito/mockito/issues/1110), I took a look at dexmaker code in case I need to be cautions about breaking some compatibility :) I found a class that imports a couple of internal Mockito classes (org.mockito.internal).

**Comment by drewhannay** [comment]
It'd be great to clean this up. Luckily it looks like all the internal api usages are centralized in [InvocationHandlerAdapter](https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito/src/main/java/com/android/dx/mockito/InvocationHandlerAdapter.java) (and there's only a few).

Do you have any more info you can provide on what can be used instead of these internal classes / interfaces?

**Comment by moltmann** [comment]
When trying to convert the non-inline dexmaker mockmaker I am currently stuck in the problem that

Mockito.framework().getInvocationFactory().createInvocation ... takes a Callable for the read-method. If the real method throws an non-Exception-Throwable the realmethod-Callable cannot re-throw this. Wrapping it in a InvocationTargetException hides the lowest stack frame.

**Comment by moltmann** [comment]
@mockitoguy : Can you recommend how to throw a non-Exception-Throwable from a realMethod used in Mockito.framework().getInvocationFactory().createInvocation(...)  ?

**Comment by moltmann** [comment]
Here is the prototype: https://github.com/linkedin/dexmaker/compare/master...moltmann:NoInternalAPIsRegularMockitoMockMaker?expand=1#diff-0fb129afa3b06051a7b3c353ae4f125c

**Comment by drewhannay** [comment]
@moltmann is there still work left to do on this one?

**Comment by moltmann** [comment]
pull #93 and we are done.

**Comment by drewhannay** [comment]
Thanks @moltmann!
