### ISSUE TITLE
Which version of dexmaker-mockito supports mocking final in androidTest

### ISSUE THREAD

**Issue by dillonykyang** [linkedin/dexmaker#77]
Hi guys,

I've been trying to mock the final classes with older version of Mockito - and Dexmaker-Mockito. However, I couldn't get them to work and I am getting several exceptions with different versions and approaches. I've done some digging online and said mocking final classes in Android Instrumentation Tests aren't possible. Is that the case?

Thanks!

```java.lang.NoClassDefFoundError: Could not initialize class com.android.dx.stock.ProxyBuilder```

**Comment by moltmann** [comment]
Hi,

mocking final methods on Android is not possible yet. It will be possible
in the future. You'll need

   - mockito 2.12
   - a yet not released version of dexmaker that includes this patch
   <https://github.com/linkedin/dexmaker/commit/e95a0a9e838ebd52858ff4d7ee0fd4f962e062d3>
   and
   - Android P, which is not yet released. You can build Android from the
   AOSP/master source tree and it will work, though.

All this is not yet released, hence there might be changed.

Philip

**Comment by drewhannay** [comment]
@dillonykyang I released version 2.16.0 today, which is the first release that includes the new `dexmaker-mockito-inline` artifact. Please try it out and let us know if you have any issues!

Keep in mind, as @moltmann mentioned, this new artifact can only be used if you're running your tests on Android P (which is currently in Developer Preview 1)

**Comment by nikhilsol89** [comment]
@drewhannay @moltmann   Can this version be used to mock external libraries final classes as well ? Like In android app we require to mock third party libs like OkHttpClient3 or Retrofit and similarly others as well.

**Comment by moltmann** [comment]
There is no fundamental reason why this should not work with 3rd party libs. Please try it out and file bugs if it does not work.

**Comment by jaredsburrows** [comment]
@drewhannay Why does this only work on Android P? Does this mean we will have to use test emulators running Android P? There is no way to mock final on Android?

**Comment by moltmann** [comment]
This relies on JVMTI. JVMTI was added in O but some features were added only in P.

So yes. There will be some tests that you cannot run on older platforms. With time this will become a smaller issues.

**Comment by jaredsburrows** [comment]
@moltmann So this is the only solution for now? Android P? Have you taken a look at: https://github.com/tmurakami/dexopener?

**Comment by moltmann** [comment]
This was mainly targeted to Android framework classes. They are actually already loaded _before_ the process is even created. If you want to deal with finals of your own app or libraries, you can just pre-process it and remove them before the app gets loaded on the device. Or you can use dexopener or any other solution.

**Comment by nikhilsol89** [comment]
@drewhannay @moltmann When can we expect the support for devices running on Pre P Android Version.Seems to be some problems running with Android P don't know if they this library specific or due to Android P's DP1 issues.
Can brief about the same.

**Comment by moltmann** [comment]
Sorry. As of new this depends on Android P. If someone finds a way to make this work without JVMTI, I am happy to change it.

On the other hand I am sure Espresso or whatever other lib is causing problem will soon support Android P.
